/*
 * Gridly API
 * Gridly API documentation
 *
 * The version of the OpenAPI document: 3.21.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.gridly.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.io.Serializable;

/**
 * Dependency
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class Dependency implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_SOURCE_COLUMN_ID = "sourceColumnId";
  @SerializedName(SERIALIZED_NAME_SOURCE_COLUMN_ID)
  private String sourceColumnId;

  public static final String SERIALIZED_NAME_TARGET_COLUMN_ID = "targetColumnId";
  @SerializedName(SERIALIZED_NAME_TARGET_COLUMN_ID)
  private String targetColumnId;

  public Dependency() { 
  }

  public Dependency id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public Dependency sourceColumnId(String sourceColumnId) {
    
    this.sourceColumnId = sourceColumnId;
    return this;
  }

   /**
   * Get sourceColumnId
   * @return sourceColumnId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getSourceColumnId() {
    return sourceColumnId;
  }


  public void setSourceColumnId(String sourceColumnId) {
    this.sourceColumnId = sourceColumnId;
  }


  public Dependency targetColumnId(String targetColumnId) {
    
    this.targetColumnId = targetColumnId;
    return this;
  }

   /**
   * Get targetColumnId
   * @return targetColumnId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getTargetColumnId() {
    return targetColumnId;
  }


  public void setTargetColumnId(String targetColumnId) {
    this.targetColumnId = targetColumnId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Dependency dependency = (Dependency) o;
    return Objects.equals(this.id, dependency.id) &&
        Objects.equals(this.sourceColumnId, dependency.sourceColumnId) &&
        Objects.equals(this.targetColumnId, dependency.targetColumnId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, sourceColumnId, targetColumnId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Dependency {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    sourceColumnId: ").append(toIndentedString(sourceColumnId)).append("\n");
    sb.append("    targetColumnId: ").append(toIndentedString(targetColumnId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

