name: Gridly Java SDK

on:
  push:
    branches: [ main ]
    tags: 
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2.1.3
      with:
        arguments: build

    - name: Get version
      run: |
        VER=$(cat VERSION)
        echo "RELEASE_VERSION=$VER" >> $GITHUB_ENV

    - name: Archive Artifact
      uses: actions/upload-artifact@v4
      with:
        name: com.gridly.java-sdk-${env.RELEASE_VERSION}
        path: build/libs/*.jar
        retention-days: 1
        if-no-files-found: error

    - name: Github Release
      uses: softprops/action-gh-release@v1
      id: create_release
      with:
        draft: false
        prerelease: true
        tag_name: ${{ env.RELEASE_VERSION }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
